### ISSUE TITLE
Add scikit-fuzzy as official dependency, push new version to PyPi

### ISSUE THREAD

**Issue by JDWarner** [twmeggs/anfis#1]
Scikit-Fuzzy is now on PyPi, so it can be formally added as a dependency! `setup.py` and the README should be updated.

I'd be happy to do this, if you'd like me to make a PR.

**Comment by gaojun0827** [comment]
Hi,I used anfis to learn my training set,it works,but the membership function didn't change,why?

**Comment by gcunhase** [comment]
Adding a comment to that, how can I plot the membership functions and learned rules? If possible, I'd wanna see the before and after training rules.

**Comment by twmeggs** [comment]
Hi @JDWarner 
I've finally added to the official dependency here on Github, changed setup.py and the README.  I will push this update to PyPi on Monday.
Thanks

**Comment by twmeggs** [comment]
new release uploaded to PyPi
