### ISSUE TITLE
http://www.bdmg.com.ar/?page_id=176 link is not opening

### ISSUE THREAD

**Issue by hemantbansal** [twmeggs/anfis#9]
As you told there is a document related to ANFIS at following link. This link is not working.
http://www.bdmg.com.ar/?page_id=176

**Comment by twmeggs** [comment]
Yep. Will correct broken link. Document is available here:
https://mran.microsoft.com/snapshot/2017-04-14/web/packages/anfis/anfis.pdf

**Comment by hemantbansal** [comment]
Thanks
